name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_spinkit: ^5.2.1 # for loading animation
  location: ^7.0.1 # location package
  geocoding: ^3.0.0 # unpacking coordinates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Warpen
      fonts:
        - asset: font/Warpen.ttf
        - asset: font/Warpen.otf
    - family: Poppins
      fonts:
      - asset: font/Poppins-Regular.ttf
    - family: ChakraPetch
      fonts:
      - asset: font/ChakraPetch-Regular.ttf

    - family: DMSans
      fonts:
      - asset: font/DMSans-VariableFont.ttf
    - family: Sour Gummy
      fonts:
      - asset: font/SourGummy-VariableFont_wdth,wght.ttf

    - family: DM Serif Display
      fonts:
      - asset: font/DMSerifDisplay-Italic.ttf
      - asset: font/DMSerifDisplay-Regular.ttf